name: Upload Python Package

on:
  release:
    types: [published]

env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
        pip install --upgrade twine
        
    - name: Build package
      run: python -m build
      
    - name: Publish package
      run: |
        python -m twine upload -r testpypi dist/*
